#default profile

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.cadieux: DEBUG
    org.hibernate:SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

#h2 profile
spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:team-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always

---

#for docker

spring:
  datasource:
    url: jdbc:mysql://mysql2/team-db
    username: user
    password: pwd
  jpa:
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: docker
  sql:
    init:
      platform: mysql
      mode: always

server.port: 8080

spring.datasource.hikari.initialization-fail-timeout: 60000