server:
  error:
    include-message: always
spring.data.mongodb:
  host: localhost
  port: 27017
  database: leagues
logging:
  level:
    root: INFO
    com.banklister: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  mongodb:
    embedded:
      version: 5.0.2
---
spring:
  config:
    activate:
      on-profile: docker

spring.data.mongodb.host: mongo

server.port: 8080
